### ISSUE TITLE
How to add recurring payments to Paypal?

### ISSUE THREAD

**Issue by biapar** [Merchello/Merchello#1329]
Hi,

my store need to manage subscriptions. So each product can be payed each months or years. I think that I need to customize product and payment gateway. 
Product because I need to say price x time and how long ( each months for 12 months ) and payment gateway ( Paypal ) to manage recurring payments. 
How do this? Can someone write some help? Thx.

**Comment by rustyswayne** [comment]
Hi @biapar - You're right, this would be something done with the payment provider.  Be best to reach out to the Scandia consulting guys on it.  I've done some recurring stuff in Braintree here: https://github.com/Merchello/Merchello.Plugin.Payment.Braintree.  PayPal owns Braintree and I know adding a PayPal method would not be that hard ... so that may be an option.

**Comment by biapar** [comment]
Hi, Paypal IPN and SDK support recurring payments. What mean PayPal owns Braintree? Do I need to check this plugin to se how to made a product as a subscription?

**Comment by rustyswayne** [comment]
The way I've done it in the past is to let the payment provider handle the subscription and generate an invoice when the payment provider notifies the application that a payment has occurred - usually via a webhook.  

With respect to Braintree, all I meant was that Paypal (the company) bought Braintree (https://www.braintreepayments.com/) and you can accept Paypal payments through Braintree - https://developers.braintreepayments.com/javascript+dotnet/guides/paypal/overview.

I've already wrapped most of the Braintree API in the provider above and was saying that adding the PayPal payment method to that provider rather than doing all the code for the PayPal provider might save you some time.   I've been meaning to add PayPal to the Braintree provider for some time but have not gotten to it yet.
