### ISSUE TITLE
Binary File Errors Warning in Umbraco 7.4 Beta

### ISSUE THREAD

**Issue by Nicholas-Westby** [Merchello/Merchello#1515]
I just installed Merchello 1.13.2 into the beta for Umbraco 7.4 and noticed this scary sounding message:

![warning](https://cloud.githubusercontent.com/assets/5933222/11880603/878d1e58-a4b6-11e5-8cf3-cbdaf06ffcee.png)

The site seems to work, but I thought I'd let you know that people installing this may be seeing that warning.

**Comment by rustyswayne** [comment]
Err - thought I caught all those.  I know installing merchello and then the stand alone bazaar does not have the issue.

That being said, the message is overly aggressive and it does work ...

**Comment by Nicholas-Westby** [comment]
Gotcha. Out of curiosity, what causes the "binary file errors detected" message? I'm developing some packages and would like to know how to avoid that, if you don't mind.

**Comment by rustyswayne** [comment]
It is going to be a dependency version reference somewhere.  It could be any one of the Umbraco dependencies (or one of their dependencies) that was not updated correctly.  It's hard to track in this case since the Merchello.Bazaar.dll should be the same in both the stand alone and the combined ... but obviously something is different.

**Comment by rustyswayne** [comment]
This was fixed in 1.13.3
