### ISSUE TITLE
Question: Is it advisable to use Merchello to build an e-commerce website that handles more than 50K products?

### ISSUE THREAD

**Issue by premkumaranand** [Merchello/Merchello#1518]
In my previous project, there was a case where we had around 2000+ locations and we structured it like this:

    Locations
    |------> Location1
    |------> Location2
    |------> Location3
    |------> ......
    |------> Location2000

It blew up the performance of the website as it is not a good practice to hold many child nodes under one parent node. We fixed it by separating the locations across regions and areas. 

Now that we are speaking about 50K+ products and Merchello leverages UmbracoContext Cache, will it affect the performance of the site? 

We can run a quick test but wanted to check with the community before we spend our first penny on that effort.

We are considering Umbraco/Merchello mainly because it is open source (easy to bend rules or extend) and almost free, and we are a startup to justify the economical approach.

**Comment by rustyswayne** [comment]
Post Merchello 1.12.0, products do not need to be created in Umbraco content.  Instead we use the same Examine (Lucene) based cache and have created virtual content so there should be no problem with Umbraco content nodes.

We also included a Product List View data type which allows you to associate collections of products with a content node - like a category for example.

Try downloading and installing the Bazaar starter kit and browsing the back office.  It uses both IProductContent and the collections with the default data.

**Comment by premkumaranand** [comment]
Thanks @rustyswayne. I have been playing around with the Bazaar for a few weeks on and off now. I'm clear about the structure that Merchello follows to avoid having to create products as content nodes as well, clever. 

I was doubtful from the experience that I have mentioned. The bottleneck in that case was the 2000+ locations going into one cache object, because all locations are under one container parent node. Any query into the Umbraco Cache took around 4-5 seconds. So, I'm curious to know how the virtual product contents are cached in Merchello. If I have 50K products, will those be under one container content (in cache)? 

If you know of any cases where Merchello had been used in this medium scale and any best practices that would be great to learn.

But any ways, meanwhile, I'll try a test run tomorrow by adding 1000s of products and see how it performs.

**Comment by rustyswayne** [comment]
I know of one site that has over 25,000 products and have not heard any complaints.

The "caching" in Merchello is actually completely different from Umbraco due to the potentially very large collections of both products and order/invoice history.  In general, queries for collections of products, customers, invoices and orders first hit the database to return a page of keys (only the GUIDs that match records for the query) and then, in order to return the full object an attempt is made to find a matching document in the Examine index.  If a document is found, the object is deserialized from Examine, if not, the full graph query is done for that particular missing object, which is then serialized and reindexed in Examine and then returned as part of the result set.

**Comment by premkumaranand** [comment]
That explains, @rustyswayne. Excellent design choice. Thanks for your time. I'll post back any results that we find. FYI, modanchi.com is the website we are looking to use Merchello for. This will be a bigger platform with a number of suppliers + drop-shipping.. Will be a good case for Merchello.
