### ISSUE TITLE
write.lock being used by another process

### ISSUE THREAD

**Issue by jessetinell** [Merchello/Merchello#1533]
[UmbracoTraceLog.Jesse.txt](https://github.com/Merchello/Merchello/files/85759/UmbracoTraceLog.Jesse.txt)
I have multiple sites/websites in one Umbraco installation.

When one site is initialized (and running correctly) and when trying to initialize the other sites I get this error:
The process cannot access the file '[path]\App_Data\TEMP\ExamineIndexes\CT6729\Merchello\Customer\Index\write.lock' because it is being used by another process.

The first site/application is started and running correctly.

Anyone got some ideas?

Umbraco: 7.3.4
Merchello: 1.13.3

**Comment by rustyswayne** [comment]
Hmm - how do you have your sites setup in IIS?  Do you have a single site or multiple sites with multiple application pools?

**Comment by jessetinell** [comment]
I somehow got it to work again but I don't know how, really. 

My setup is multiple sites and application pools. This has not happened again in this past week and I can't reproduce it either.

Just have to let it roll for now.

Thank you for the quick response though (and sorry for my slow response)

**Comment by jessetinell** [comment]
This problem is back. Not changed anything on the server either

**Comment by leen3o** [comment]
Noticed this in the Umbraco issues. See first link as might be an issue with server update.

http://issues.umbraco.org/issue/U4-6338
http://issues.umbraco.org/issue/U4-6321

**Comment by jessetinell** [comment]
I have the same problem locally though. 

**Possible temporary solution:**
I found that republishing the entire site and restarting the application worked.

**Comment by rustyswayne** [comment]
@jessetinell Are you multiple sites in IIS pointed to a single Umbraco instance?

**Comment by jessetinell** [comment]
Yes @rustyswayne 

The lucene indexing for all sites are trying to access the same file in some point. And it's always the 'Merchello\Customer\Index\write.lock' that's failing. Maybe Merchello is doing something different than Umbraco or not "releasing" the files correctly (just my spontaneous thoughts).

**More permanent/hacky "solution"?** (for those who need a quick-fix)
I created a TEMP-folder for each website and created a virtual directory in IIS named TEMP (for each website/language pointing to respective folder).

**Comment by rustyswayne** [comment]
@jessetinell I think this is going to be an issue in your IIS setup.  The same index should not be accessed by multiple application pools - that will cause a lock.  My guess is you've seen this mostly in Merchello since the indexes are being written to much more frequently than Umbraco - but you will like have the same issue if your sites have membership where users are constantly being added from the various applications.

This is different than a load balanced setup where there are multiple instances of Umbraco each running in their own instance.  In this case, you still have multiple indexes with the respective server name in the path.  

I think you might eventually have problems with the umbraco.config file as well - since that xml file is written to every time content is saved and published.  If two authors are saving at the same time, it may become an issue.  Please feel free to double check me on this.  Maybe start a forum thread on our.umbraco.org and let me know the URL and I'll follow the discussion.
