### ISSUE TITLE
Update FastTrack package to use new Umbraco pickers for media and content

### ISSUE THREAD

**Issue by t9creative** [Merchello/Merchello#2057]
Hello.  I have a fresh install of Umbraco 7.7.2 and a fresh install of Merchello 2.6.0. I have also installed FastTract 2.6.0.

When I go to the initially installed products, click on one and then the Extended Content > Images tab, the image doesn't come up and the picker to even select one doesn't display.  There is a javascript error:

`TypeError: a.indexOf is not a function`

**Comment by YodasMyDad** [comment]
I am taking a guess this is to do with the new umb:identifier change in 7.7 ... The FastTrack is using the old pickers still. Will update issue to change FastTrack to use new pickers (Try changing the DocType pickers in FastTrack to the new Umb pickers released with V7, and I suspect it will sort this)

**Comment by John-gecko** [comment]
For ref when someone goes to do this
I needed to change the following files to get it working:
_ProductBox.cshtml

\Umbraco\App_Plugins\FastTrack\Views\CheckoutSummary
BasketSummary.cshtml
InvoiceSummary.cshtml
SalesReceipt.cshtml

\Umbraco\AppPlugins\Merchello\views\StoreBasket\BasketForm.cshtml \Umbraco\AppPlugins\Merchello\views\StoreWishList\WishListForm.cshtml

using the newer format of 
var images = Model.GetPropertyValue<IEnumerable<IPublishedContent>>("image");
to get the images selected for the product

obviously for fastrack it only uses 1 image so you need to get the first in the list var image = images.FirstOrDefault();

or the picker needs to change to be a single rather than multi picker

Cheers
J

**Comment by joecklau** [comment]
Macro has a clear guideline to tell which picker should be selected to fix the problem:
https://our.umbraco.com/forum/templates-partial-views-and-macros/86532-string-2293-is-not-a-valid-udi-from-images-in-763#comment-274165

**Comment by YodasMyDad** [comment]
Done in 2.7.0

**Comment by biapar** [comment]
For 2.6.0 version:

var image = Model.GetPropertyValue<IEnumerable<IPublishedContent>>("image").FirstOrDefault();
