### ISSUE TITLE
App Pool recycle clears the cart 

### ISSUE THREAD

**Issue by FlippingKnight** [Merchello/Merchello#2136]
We are using Merchello and been doing so for a few years now.
We got one really big issue that we need help with resolving.

The problem is that whenever app pool is recycled, if the page is updated (a page refresh is enough) within 1 minute after the recycling, the cart will be empty.
The theory is that it takes time for Umbraco to rebuild and if you try to reach the site during this time MerchelloItemCache will not be accessible.

We have tried changing the app pool settings but nothing seems to work.

Any advice is greatly appreciated.

Thanks!

//
Tobias

**Comment by ronaldbarendse** [comment]
Looking at the Merchello source, the customer is identified by using the `merchello` cookie, so that should survive restarts... Just double check that the same customer is returned (same GUID)...

The basket is first retrieved from the Umbraco `RuntimeCache` and if not found from the Merchello `ItemCacheService`. This service uses the database, so there should be rows for the basket: make sure you are saving the basket after changes (`Basket.Save();`). If you're using the `BasketControllerBase` as controller base class this is already done for you in `AddBasketItem()`.

Otherwise: isn't this related to session state that is stored `InProc` by default and therefore gets emptied out on application restarts/recycles?

**Comment by FlippingKnight** [comment]
Thanks for the answer ronaldbarendse! I'll take a closer look at the merchello cookies.

I think it indeed is related to the session state. Thank you again! I now got some more ideas on how to debug

**Comment by eriksimonic** [comment]
@FlippingKnight Do you use InProc session state? If so try to configure SqlSession state. Solved a lot of my problems.
